### ISSUE TITLE
Correcciones pagina web

### ISSUE THREAD

**Issue by dsalas56** [CIAT-DAPA/aeps_open#9]
@juangarc 

- [ ] Agregar nuevo contenido en Media, casos de exito y Articulos
- [ ] Hacer los cambios de texto
- [ ] Hacer cambios de iconos e imagenes
- [ ] Actualizar los servcios ( añadiendo captura de datos)
- [ ] Eliminar taller de mineria de datos de [herramientas]
- [ ] Eliminar el primer articulo de 2020 [application of big data analytics and AI...]

@dsalas56 
- [x] Hacer las correcciones alusivas a los iconos e imagenes y enviar a Juan Camilo el material que necesite

**Comment by stevensotelo** [comment]
@juangarc 
- [ ] Pendiente agregar datos a articulos y media

@dsalas56 
- [ ] Pendiente enviar imagenes de articulos
